# Generated by Django 3.2 on 2021-04-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_site', '0002_auto_20210415_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='number',
            new_name='num',
        ),
    ]
