# Generated by Django 3.2 on 2021-04-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0003_rename_number_section_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grader', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.account')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.course')),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='members',
            field=models.ManyToManyField(related_name='sections', to='scheduler_app.Account'),
        ),
        migrations.DeleteModel(
            name='SectionMembership',
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(through='scheduler_app.CourseMembership', to='scheduler_app.Account'),
        ),
    ]
