# Generated by Django 3.2 on 2021-04-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0004_auto_20210418_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='courses', through='scheduler_app.CourseMembership', to='scheduler_app.Account'),
        ),
    ]
