# Generated by Django 3.2 on 2021-04-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0005_alter_course_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='members',
        ),
        migrations.AddField(
            model_name='coursemembership',
            name='sections',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='section',
            name='TA',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ta', to='scheduler_app.account'),
        ),
    ]
