# Generated by Django 3.2 on 2021-04-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0005_alter_course_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='num',
            field=models.CharField(max_length=1023),
        ),
    ]
