# Generated by Django 3.2 on 2021-04-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0006_auto_20210427_1241'),
        ('scheduler_app', '0007_alter_section_course'),
    ]

    operations = [
    ]
