# Generated by Django 3.2.1 on 2021-05-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0010_auto_20210427_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='skills',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='office_hours',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
