# Generated by Django 3.2.3 on 2021-05-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0014_auto_20210516_1506'),
        ('scheduler_app', '0014_auto_20210516_2046'),
    ]

    operations = [
    ]
