# Generated by Django 3.2.1 on 2021-05-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0015_alter_section_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='scheduler_app.account'),
        ),
    ]
